###
GET http://localhost:3000

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Bob"
}

###
GET http://localhost:3000/users/1

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users/1/posts
Content-Type: application/json

{
    "content": "Hello, Rails!"
}

###
GET http://localhost:3000/users/1/posts/11

###
PUT http://localhost:3000/users/1/posts/11
Content-Type: application/json

{
    "content": "Goodbye Rails!"
}

###
DELETE http://localhost:3000/users/1/posts/9

###
GET http://localhost:3000/users/1/posts
